server:
  servlet:
    context-path:
  port: 8080
  shutdown: graceful
spring:
  #  profiles:
  #    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: Asia/Shanghai
    default-property-inclusion: always
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      database: 0



mybatis-plus:
  configuration:
    use-generated-keys: true
    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  executor-type: BATCH

